### ISSUE TITLE
Analysis results metadata extraction language

### ISSUE THREAD

**Issue by tom114** [phac-nml/irida#159]
In the case of writing back metadata from an analysis pipeline's output files, I could see there being a lot of overlap with how files are structured and formatted and as such we could have generic parsing functions for common cases.
A domain-specific language (DSL) for handling extraction of metadata from analysis output files could be useful. 

Some common output file formats:

- tabular data
	- essentially a list of maps (each row is a map of {field name => cell value})
- numeric matrix data 
	- also a list of maps
	- MLST-like results where rownames are sample IDs, column names are MLST marker IDs and cell values are the allele calls
- JSON
	- variable format, but could specify how to access fields of interest, e.g. 
		- first item of list
		- with nested map `{"data":{"results":{"result":...}}}` `get in ["data", "results", "result"]`

We could have the rules for extracting metadata from analysis output files encoded in a human readable/writable format like YAML. For example, a spec file for parsing SISTR metadata:

```yaml
files:
	sistr-predictions.json:
		type: json
		format: List<Map<String, Object>> # or something like that
		accessor: first item # (results) -> results.get(0)
		fields:
			serovar: 
				name: SISTR serovar
				type: String
			cgmlst_subspecies: 
				name: SISTR cgMLST Subspecies
				type: String
			cgmlst_ST: 
				name: SISTR cgMLST Sequence Type
				type: Integer
			# other fields...
	sistr-cgmlst-profiles.csv:
		type: csv
		format: List<Map<String, Object>> # list of rows with field to value
		accessor: first item # map of first row
		fields:
			__all__: true
			__type__: Integer|null
	# etc
```

What do you guys think?

Imported from GitLab issue #645.  Originally posted on 2018/05/25 04:21PM\Posted by Peter Kruczkiewicz
